import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const inter = Inter({subsets:['latin'],variable:'--font-inter'});

const instrumentSerif = Instrument_Serif({
  weight: "400",
  variable: "--font-instrument-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zeuxis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", instrumentSerif.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col gap-8 justify-between bg-linear-to-tr from-gray-100 via-gray-200 to-gray-300 p-2 md:p-3">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
